#!/bin/bash

set -euo pipefail

source /usr/share/yunohost/helpers
source "$(dirname "$0")/_common.sh"

load_settings

ynh_script_progression --message="Backing up application data..." --weight=2

ynh_backup --src_path="$install_dir"
ynh_backup --src_path="$data_dir"

ynh_script_progression --message="Backup completed." --weight=1
