#!/bin/bash

set -euo pipefail

source /usr/share/yunohost/helpers
source "$(dirname "$0")/_common.sh"

old_domain="$YNH_APP_OLD_DOMAIN"
old_path="$YNH_APP_OLD_PATH"
new_domain="$YNH_APP_NEW_DOMAIN"
new_path="$YNH_APP_NEW_PATH"

load_settings

ynh_script_progression --message="Updating URL settings..." --weight=2

ynh_change_url_nginx_config --domain="$old_domain" --path="$old_path" --new_domain="$new_domain" --new_path="$new_path"

ynh_app_setting_set --app="$app" --key=domain --value="$new_domain"
ynh_app_setting_set --app="$app" --key=path --value="$new_path"

yunohost app ssowatconf

ynh_script_progression --message="URL update completed." --weight=1
