#!/bin/bash

set -euo pipefail

source /usr/share/yunohost/helpers
source "$(dirname "$0")/_common.sh"

old_domain=$domain
old_path=$path

new_domain=$new_domain
new_path=$new_path

domain=$new_domain
path=$new_path

ynh_script_progression --message="Updating configuration..." --weight=1

ynh_replace_string --match="https://${old_domain}${old_path}" --replace="https://${new_domain}${new_path}" --target_file="$data_dir/config/app.conf.php"
ynh_app_setting_set --app="$app" --key=domain --value="$new_domain"
ynh_app_setting_set --app="$app" --key=path --value="$new_path"

ynh_script_progression --message="Updating nginx configuration..." --weight=2

ynh_add_nginx_config

yunohost app ssowatconf

ynh_script_progression --message="Change URL completed." --weight=1
