#!/bin/bash

set -euo pipefail

source /usr/share/yunohost/helpers
source "$(dirname "$0")/_common.sh"

phpversion=$(ynh_app_setting_get --app="$app" --key=phpversion || true)

ynh_restore

yunohost app ssowatconf

